/* 
 * Dyspatch API
 *
 * # Introduction  The Dyspatch API is based on the REST paradigm, and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs, and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.  ## API Client Libraries Dyspatch provides API Clients for popular languages and web frameworks.  - [Java](https://github.com/getdyspatch/dyspatch-java) - [Javascript](https://github.com/getdyspatch/dyspatch-javascript) - [Python](https://github.com/getdyspatch/dyspatch-python) - [C#](https://github.com/getdyspatch/dyspatch-dotnet) - [Go](https://github.com/getdyspatch/dyspatch-golang) - [Ruby](https://github.com/getdyspatch/dyspatch-ruby) 
 *
 * The version of the OpenAPI document: 2020.04
 * Contact: support@dyspatch.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Dyspatch.Api;
using IO.Dyspatch.Model;
using IO.Dyspatch.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Dyspatch.Test
{
    /// <summary>
    ///  Class for testing TemplatesRead
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplatesReadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplatesRead
        //private TemplatesRead instance;

        public TemplatesReadTests()
        {
            // TODO uncomment below to create an instance of TemplatesRead
            //instance = new TemplatesRead();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplatesRead
        /// </summary>
        [Fact]
        public void TemplatesReadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TemplatesRead
            //Assert.IsInstanceOfType<TemplatesRead> (instance, "variable 'instance' is a TemplatesRead");
        }


        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
